image: golang:latest

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is mydomainperso.com, and that your repository is repos/projectname, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/mydomainperso.com/repos/projectname 
# Thus, making a symbolic link corrects this.
before_script:
  - ln -s /builds /go/src/gitlab.com
  - cd /go/src/gitlab.com/passelecasque/varroa

stages:
  - test
  - build

format:
  stage: test
  script:
    - go get github.com/docopt/docopt-go
    - go get github.com/wcharczuk/go-chart
    - go get github.com/thoj/go-ircevent
    - go get github.com/stretchr/testify/assert
    - go get github.com/gregdel/pushover
    - go get github.com/dustin/go-humanize
    - go get github.com/gorilla/mux
    - go get github.com/gorilla/websocket
    - go get gopkg.in/vmihailenco/msgpack.v2
    - go get golang.org/x/net/publicsuffix
    - go get github.com/sevlyar/go-daemon
    - go get github.com/subosito/norma
    - go get github.com/goji/httpauth
    - go get github.com/jasonlvhit/gocron
    - go get github.com/mholt/archiver
    - go get github.com/howeyc/gopass
    - go get gopkg.in/yaml.v2
    - go get github.com/pkg/errors
    - go tool vet -composites=false -shadow=true *.go
    - go test -race $(go list ./... | grep -v /vendor/)

compiled_varroa_dev:
  stage: build
  script:
    - go get github.com/docopt/docopt-go
    - go get github.com/wcharczuk/go-chart
    - go get github.com/thoj/go-ircevent
    - go get github.com/stretchr/testify/assert
    - go get github.com/gregdel/pushover
    - go get github.com/dustin/go-humanize
    - go get github.com/gorilla/mux
    - go get github.com/gorilla/websocket
    - go get gopkg.in/vmihailenco/msgpack.v2
    - go get golang.org/x/net/publicsuffix
    - go get github.com/sevlyar/go-daemon
    - go get github.com/subosito/norma
    - go get github.com/goji/httpauth
    - go get github.com/jasonlvhit/gocron
    - go get github.com/mholt/archiver
    - go get github.com/howeyc/gopass
    - go get gopkg.in/yaml.v2
    - go get github.com/pkg/errors
    - go build -o varroa
#    - go build -race -ldflags "-extldflags '-static'" -o varroa
  artifacts:
    paths:
    - varroa
    name: "varroa-dev-${CI_COMMIT_REF_NAME}"
    expire_in: 4 weeks
  except:
    - tags  
    
compiled_varroa_released_version:
  stage: build
  script:
    - go get github.com/docopt/docopt-go
    - go get github.com/wcharczuk/go-chart
    - go get github.com/thoj/go-ircevent
    - go get github.com/stretchr/testify/assert
    - go get github.com/gregdel/pushover
    - go get github.com/dustin/go-humanize
    - go get github.com/gorilla/mux
    - go get github.com/gorilla/websocket
    - go get gopkg.in/vmihailenco/msgpack.v2
    - go get golang.org/x/net/publicsuffix
    - go get github.com/sevlyar/go-daemon
    - go get github.com/subosito/norma
    - go get github.com/goji/httpauth
    - go get github.com/jasonlvhit/gocron
    - go get github.com/mholt/archiver
    - go get github.com/howeyc/gopass
    - go get gopkg.in/yaml.v2
    - go get github.com/pkg/errors
    - go build -o varroa
  artifacts:
    paths: 
    - varroa
    name: "varroa-${CI_COMMIT_REF_NAME}"
  only:
    - tags    
            
