image: golang:latest

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5
  - make deps

stages:
  - test
  - build

format:
  stage: test
  script:
    - make test

compiled_varroa_dev:
  stage: build
  script:
    - cd cmd/varroa
    - go build -v -o ../../varroa
    - cd ../varroa-fuse
    - go build -v -o ../../varroa-fuse
    - cd ../..
    - cp cmd/varroa/bash_completion varroa_bash_completion
  artifacts:
    paths:
    - varroa
    - varroa_bash_completion
    - varroa-fuse
    - script/send-to-varroa.js
    name: "varroa-dev-${CI_COMMIT_REF_NAME}"
    expire_in: 4 weeks
  except:
    - tags

compiled_varroa_released_version:
  stage: build
  script:
    - cd cmd/varroa
    - go build -o ../../varroa
    - cd ../varroa-fuse
    - go build -o ../../varroa-fuse
    - cd ../..
    - cp cmd/varroa/bash_completion varroa_bash_completion
  artifacts:
    paths:
    - varroa
    - varroa_bash_completion
    - varroa-fuse
    - script/send-to-varroa.js
    name: "varroa-${CI_COMMIT_REF_NAME}"
  only:
    - tags





test_assistance:
  stage: test
  script:
    - make all
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"

