# Reference: https://github.com/golangci/golangci-lint

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - lll
    - maligned
    # TODO: enable and fix more things
    - deadcode
    - goconst
    - scopelint
    - gocyclo
    - structcheck
    - gosec
    - megacheck
    - errcheck
    - varcheck
    - gocritic
    - golint
    - goimports
    - prealloc
